# Generated by Django 5.1.5 on 2025-01-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
